[pytest]
pythonpath = src
python_files = tests.py test_*.py *_tests.py *_test.py
addopts = --strict-markers
markers =
    integration: mark test as an integration test
    unit: mark test as a unit test
    django_db: mark test to have access to the database and transaction rollback (provided by pytest-django)