# Generated by Django 6.0.4 on 2026-05-16 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CastMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("ACTOR", "ACTOR"), ("DIRECTOR", "DIRECTOR")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "cast_member",
            },
        ),
    ]
